name: assets_manager
description: Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_picker: ^2.0.2
  flutter_datetime_picker: ^1.5.1


  #Cơ sở dữ liệu
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  provider: ^6.0.0
  firebase_database: ^10.1.2
  cloud_firestore: ^4.7.1

  image_picker: ^0.8.7
  firebase_storage: ^11.1.2

  modal_bottom_sheet: ^3.0.0-pre
  #Quét mã QR
  barcode_widget: ^2.0.3
  flutter_barcode_scanner: ^2.0.0

  #Trang giao diện đầu tiên
  avatar_glow: ^2.0.2

  #Định dạng textflied
  fluttertoast: ^8.2.1
  flutter_format_money_vietnam: ^0.0.2

  #File PDF
  pdf: ^3.8.4
  pdfx: ^2.3.0
  path_provider: ^2.0.15
  flutter_pdfview: ^1.3.0

  share_plus: ^6.3.4

  http: ^0.13.5
  permission_handler: ^10.2.0
  dio: ^5.1.2

  circular_countdown: ^2.1.0
  gap: ^2.0.0
  timer_controller: ^1.0.0
  dropdown_search: ^5.0.6
  horizontal_data_table: ^4.1.2
  charts_flutter: ^0.12.0
  font_awesome_flutter: ^10.4.0
  equatable: ^2.0.5

  #Lưu bộ nhớ tạm
  shared_preferences: ^2.1.1

  #Đăng nhập bằng vân tay
  local_auth: ^2.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/font/
  - assets/font/Open_Sans/
  - assets/font/roboto/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/font/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/font/Open_Sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/font/Open_Sans/OpenSans-Bold.ttf
          weight: 400
        - asset: assets/font/Open_Sans/OpenSans-BoldItalic.ttf
    - family: roboto
      fonts:
        - asset: assets/font/roboto/Roboto-Regular.ttf
        - asset: assets/font/roboto/Roboto-Bold.ttf
          weight: 400
        - asset: assets/font/roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/font/roboto/Roboto-BoldItalic.ttf
    - family: Tinos
      fonts:
        - asset: assets/font/Tinos/Tinos-Regular.ttf
        - asset: assets/font/Tinos/Tinos-Bold.ttf
          weight: 200
        - asset: assets/font/Tinos/Tinos-Italic.ttf
          style: italic
        - asset: assets/font/Tinos/Tinos-BoldItalic.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
